#############################################################################
# Makefile for building: reg_qt_launcher
# Generated by qmake (1.03a) on: Tue Oct 28 14:33:07 2003
# Project:  reg_qt_launcher.pro
# Template: app
# Command: $(QMAKE) reg_qt_launcher.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -I/usr/include/freetype2 -I/usr/include/freetype2/freetype -O2 -march=i386 -mcpu=i686 -fno-use-cxa-atexit -fno-exceptions -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -I/usr/include/freetype2 -I/usr/include/freetype2/freetype -O2 -march=i386 -mcpu=i686 -fno-use-cxa-atexit -fno-exceptions -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -Iinclude -I/usr/include/libxml2 -I${HOME}/RealityGrid/reg_gsoap_build -I${REG_STEER_HOME}/include -I$(QTDIR)/include -I.ui/ -Iui -I.moc/ -I$(QTDIR)/mkspecs/default
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS)  -L$(QTDIR)/lib  -L/usr/X11R6/lib -lxml2 -L${HOME}/RealityGrid/reg_gsoap_build -lREGgsoap -L${HOME}/RealityGrid/reg_steer_lib/lib32 -lReG_Steer -lqt-mt -lpthread -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY) -p
COPY_DIR = $(COPY) -pR
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = include/LauncherConfig.h \
		include/Gridifier.h \
		include/Utility.h \
		include/CheckPointTree.h \
		include/CheckPointTreeItem.h \
		include/chkptvariableform.h \
		include/JobStatusThread.h
SOURCES = src/main.cpp \
		src/LauncherConfig.cpp \
		src/Gridifier.cpp \
		src/Utility.cpp \
		src/CheckPointTree.cpp \
		src/CheckPointTreeItem.cpp \
		src/chkptvariableform.cpp \
		src/JobStatusThread.cpp
OBJECTS = .obj/main.o \
		.obj/LauncherConfig.o \
		.obj/Gridifier.o \
		.obj/Utility.o \
		.obj/CheckPointTree.o \
		.obj/CheckPointTreeItem.o \
		.obj/chkptvariableform.o \
		.obj/JobStatusThread.o \
		.obj/reglauncher.o \
		.obj/componentlauncher.o \
		.obj/RunningJobsDialog.o
FORMS = ui/reglauncher.ui \
		ui/componentlauncher.ui \
		ui/RunningJobsDialog.ui
UICDECLS = .ui/reglauncher.h \
		.ui/componentlauncher.h \
		.ui/RunningJobsDialog.h
UICIMPLS = .ui/reglauncher.cpp \
		.ui/componentlauncher.cpp \
		.ui/RunningJobsDialog.cpp
SRCMOC   = .moc/moc_Gridifier.cpp \
		.moc/moc_chkptvariableform.cpp \
		.moc/moc_reglauncher.cpp \
		.moc/moc_componentlauncher.cpp \
		.moc/moc_RunningJobsDialog.cpp
OBJMOC = .obj/moc_Gridifier.o \
		.obj/moc_chkptvariableform.o \
		.obj/moc_reglauncher.o \
		.obj/moc_componentlauncher.o \
		.obj/moc_RunningJobsDialog.o
DIST	   = reg_qt_launcher.pro
QMAKE_TARGET = reg_qt_launcher
DESTDIR  = 
TARGET   = reg_qt_launcher

first: all
####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

mocables: $(SRCMOC)

$(MOC): 
	( cd $(QTDIR)/src/moc ; $(MAKE) )

Makefile: reg_qt_launcher.pro  $(QTDIR)/mkspecs/default/qmake.conf 
	$(QMAKE) reg_qt_launcher.pro
qmake: 
	@$(QMAKE) reg_qt_launcher.pro

dist: 
	@mkdir -p .obj/reg_qt_launcher && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/reg_qt_launcher/ && $(COPY_FILE) --parents ui/reglauncher.ui.h ui/componentlauncher.ui.h ui/RunningJobsDialog.ui.h .obj/reg_qt_launcher/ && ( cd `dirname .obj/reg_qt_launcher` && $(TAR) reg_qt_launcher.tar reg_qt_launcher && $(GZIP) reg_qt_launcher.tar ) && $(MOVE) `dirname .obj/reg_qt_launcher`/reg_qt_launcher.tar.gz . && $(DEL_DIR) .obj/reg_qt_launcher

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS) 
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/main.o: src/main.cpp .ui/reglauncher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/LauncherConfig.o: src/LauncherConfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/LauncherConfig.o src/LauncherConfig.cpp

.obj/Gridifier.o: src/Gridifier.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Gridifier.o src/Gridifier.cpp

.obj/Utility.o: src/Utility.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Utility.o src/Utility.cpp

.obj/CheckPointTree.o: src/CheckPointTree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CheckPointTree.o src/CheckPointTree.cpp

.obj/CheckPointTreeItem.o: src/CheckPointTreeItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CheckPointTreeItem.o src/CheckPointTreeItem.cpp

.obj/chkptvariableform.o: src/chkptvariableform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/chkptvariableform.o src/chkptvariableform.cpp

.obj/JobStatusThread.o: src/JobStatusThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/JobStatusThread.o src/JobStatusThread.cpp

.ui/reglauncher.h: ui/reglauncher.ui 
	$(UIC) ui/reglauncher.ui -o .ui/reglauncher.h

.ui/reglauncher.cpp: .ui/reglauncher.h ui/reglauncher.ui 
	$(UIC) ui/reglauncher.ui -i reglauncher.h -o .ui/reglauncher.cpp

.ui/componentlauncher.h: ui/componentlauncher.ui .ui/reglauncher.h
	$(UIC) ui/componentlauncher.ui -o .ui/componentlauncher.h

.ui/componentlauncher.cpp: .ui/componentlauncher.h ui/componentlauncher.ui .ui/reglauncher.h
	$(UIC) ui/componentlauncher.ui -i componentlauncher.h -o .ui/componentlauncher.cpp

.ui/RunningJobsDialog.h: ui/RunningJobsDialog.ui 
	$(UIC) ui/RunningJobsDialog.ui -o .ui/RunningJobsDialog.h

.ui/RunningJobsDialog.cpp: .ui/RunningJobsDialog.h ui/RunningJobsDialog.ui 
	$(UIC) ui/RunningJobsDialog.ui -i RunningJobsDialog.h -o .ui/RunningJobsDialog.cpp

.obj/reglauncher.o: .ui/reglauncher.cpp ui/reglauncher.ui.h \
		.ui/reglauncher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/reglauncher.o .ui/reglauncher.cpp

.obj/componentlauncher.o: .ui/componentlauncher.cpp ui/componentlauncher.ui.h \
		.ui/componentlauncher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/componentlauncher.o .ui/componentlauncher.cpp

.obj/RunningJobsDialog.o: .ui/RunningJobsDialog.cpp ui/RunningJobsDialog.ui.h \
		.ui/RunningJobsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/RunningJobsDialog.o .ui/RunningJobsDialog.cpp

.obj/moc_Gridifier.o: .moc/moc_Gridifier.cpp include/Gridifier.h include/LauncherConfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_Gridifier.o .moc/moc_Gridifier.cpp

.obj/moc_chkptvariableform.o: .moc/moc_chkptvariableform.cpp include/chkptvariableform.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_chkptvariableform.o .moc/moc_chkptvariableform.cpp

.obj/moc_reglauncher.o: .moc/moc_reglauncher.cpp .ui/reglauncher.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_reglauncher.o .moc/moc_reglauncher.cpp

.obj/moc_componentlauncher.o: .moc/moc_componentlauncher.cpp .ui/componentlauncher.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_componentlauncher.o .moc/moc_componentlauncher.cpp

.obj/moc_RunningJobsDialog.o: .moc/moc_RunningJobsDialog.cpp .ui/RunningJobsDialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_RunningJobsDialog.o .moc/moc_RunningJobsDialog.cpp

.moc/moc_Gridifier.cpp: $(MOC) include/Gridifier.h
	$(MOC) include/Gridifier.h -o .moc/moc_Gridifier.cpp

.moc/moc_chkptvariableform.cpp: $(MOC) include/chkptvariableform.h
	$(MOC) include/chkptvariableform.h -o .moc/moc_chkptvariableform.cpp

.moc/moc_reglauncher.cpp: $(MOC) .ui/reglauncher.h
	$(MOC) .ui/reglauncher.h -o .moc/moc_reglauncher.cpp

.moc/moc_componentlauncher.cpp: $(MOC) .ui/componentlauncher.h
	$(MOC) .ui/componentlauncher.h -o .moc/moc_componentlauncher.cpp

.moc/moc_RunningJobsDialog.cpp: $(MOC) .ui/RunningJobsDialog.h
	$(MOC) .ui/RunningJobsDialog.h -o .moc/moc_RunningJobsDialog.cpp

####### Install

install: all 

uninstall: 

