/* checkPointTreeH.h
   Generated by gSOAP 2.3.8 from RealityGridTree.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef checkPointTreeH_H
#define checkPointTreeH_H
#include "checkPointTreeStub.h"

SOAP_BEGIN_NAMESPACE(checkPointTree)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);

SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_tree__destroyResponse
#define SOAP_TYPE_tree__destroyResponse (43)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__destroyResponse(struct soap*, const char*, int, const tree__destroyResponse *, const char*);
SOAP_FMAC3 tree__destroyResponse * SOAP_FMAC4 soap_get_tree__destroyResponse(struct soap*, tree__destroyResponse *, const char*, const char*);
SOAP_FMAC3 tree__destroyResponse * SOAP_FMAC4 soap_in_tree__destroyResponse(struct soap*, const char*, tree__destroyResponse *, const char*);

SOAP_FMAC5 tree__destroyResponse * SOAP_FMAC6 soap_new_tree__destroyResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__destroyResponse(struct soap*, tree__destroyResponse*);
SOAP_FMAC5 tree__destroyResponse * SOAP_FMAC6 soap_instantiate_tree__destroyResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__getInputFileResponse
#define SOAP_TYPE_tree__getInputFileResponse (42)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getInputFileResponse(struct soap*, const char*, int, const tree__getInputFileResponse *, const char*);
SOAP_FMAC3 tree__getInputFileResponse * SOAP_FMAC4 soap_get_tree__getInputFileResponse(struct soap*, tree__getInputFileResponse *, const char*, const char*);
SOAP_FMAC3 tree__getInputFileResponse * SOAP_FMAC4 soap_in_tree__getInputFileResponse(struct soap*, const char*, tree__getInputFileResponse *, const char*);

SOAP_FMAC5 tree__getInputFileResponse * SOAP_FMAC6 soap_new_tree__getInputFileResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__getInputFileResponse(struct soap*, tree__getInputFileResponse*);
SOAP_FMAC5 tree__getInputFileResponse * SOAP_FMAC6 soap_instantiate_tree__getInputFileResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__getSteeringCommandsResponse
#define SOAP_TYPE_tree__getSteeringCommandsResponse (41)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getSteeringCommandsResponse(struct soap*, const char*, int, const tree__getSteeringCommandsResponse *, const char*);
SOAP_FMAC3 tree__getSteeringCommandsResponse * SOAP_FMAC4 soap_get_tree__getSteeringCommandsResponse(struct soap*, tree__getSteeringCommandsResponse *, const char*, const char*);
SOAP_FMAC3 tree__getSteeringCommandsResponse * SOAP_FMAC4 soap_in_tree__getSteeringCommandsResponse(struct soap*, const char*, tree__getSteeringCommandsResponse *, const char*);

SOAP_FMAC5 tree__getSteeringCommandsResponse * SOAP_FMAC6 soap_new_tree__getSteeringCommandsResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__getSteeringCommandsResponse(struct soap*, tree__getSteeringCommandsResponse*);
SOAP_FMAC5 tree__getSteeringCommandsResponse * SOAP_FMAC6 soap_instantiate_tree__getSteeringCommandsResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__requestTerminationBeforeResponse
#define SOAP_TYPE_tree__requestTerminationBeforeResponse (40)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__requestTerminationBeforeResponse(struct soap*, const char*, int, const tree__requestTerminationBeforeResponse *, const char*);
SOAP_FMAC3 tree__requestTerminationBeforeResponse * SOAP_FMAC4 soap_get_tree__requestTerminationBeforeResponse(struct soap*, tree__requestTerminationBeforeResponse *, const char*, const char*);
SOAP_FMAC3 tree__requestTerminationBeforeResponse * SOAP_FMAC4 soap_in_tree__requestTerminationBeforeResponse(struct soap*, const char*, tree__requestTerminationBeforeResponse *, const char*);

SOAP_FMAC5 tree__requestTerminationBeforeResponse * SOAP_FMAC6 soap_new_tree__requestTerminationBeforeResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__requestTerminationBeforeResponse(struct soap*, tree__requestTerminationBeforeResponse*);
SOAP_FMAC5 tree__requestTerminationBeforeResponse * SOAP_FMAC6 soap_instantiate_tree__requestTerminationBeforeResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__getChildNodesResponse
#define SOAP_TYPE_tree__getChildNodesResponse (39)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getChildNodesResponse(struct soap*, const char*, int, const tree__getChildNodesResponse *, const char*);
SOAP_FMAC3 tree__getChildNodesResponse * SOAP_FMAC4 soap_get_tree__getChildNodesResponse(struct soap*, tree__getChildNodesResponse *, const char*, const char*);
SOAP_FMAC3 tree__getChildNodesResponse * SOAP_FMAC4 soap_in_tree__getChildNodesResponse(struct soap*, const char*, tree__getChildNodesResponse *, const char*);

SOAP_FMAC5 tree__getChildNodesResponse * SOAP_FMAC6 soap_new_tree__getChildNodesResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__getChildNodesResponse(struct soap*, tree__getChildNodesResponse*);
SOAP_FMAC5 tree__getChildNodesResponse * SOAP_FMAC6 soap_instantiate_tree__getChildNodesResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__setCheckPointDataResponse
#define SOAP_TYPE_tree__setCheckPointDataResponse (38)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__setCheckPointDataResponse(struct soap*, const char*, int, const tree__setCheckPointDataResponse *, const char*);
SOAP_FMAC3 tree__setCheckPointDataResponse * SOAP_FMAC4 soap_get_tree__setCheckPointDataResponse(struct soap*, tree__setCheckPointDataResponse *, const char*, const char*);
SOAP_FMAC3 tree__setCheckPointDataResponse * SOAP_FMAC4 soap_in_tree__setCheckPointDataResponse(struct soap*, const char*, tree__setCheckPointDataResponse *, const char*);

SOAP_FMAC5 tree__setCheckPointDataResponse * SOAP_FMAC6 soap_new_tree__setCheckPointDataResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__setCheckPointDataResponse(struct soap*, tree__setCheckPointDataResponse*);
SOAP_FMAC5 tree__setCheckPointDataResponse * SOAP_FMAC6 soap_instantiate_tree__setCheckPointDataResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__findServiceDataResponse
#define SOAP_TYPE_tree__findServiceDataResponse (37)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__findServiceDataResponse(struct soap*, const char*, int, const tree__findServiceDataResponse *, const char*);
SOAP_FMAC3 tree__findServiceDataResponse * SOAP_FMAC4 soap_get_tree__findServiceDataResponse(struct soap*, tree__findServiceDataResponse *, const char*, const char*);
SOAP_FMAC3 tree__findServiceDataResponse * SOAP_FMAC4 soap_in_tree__findServiceDataResponse(struct soap*, const char*, tree__findServiceDataResponse *, const char*);

SOAP_FMAC5 tree__findServiceDataResponse * SOAP_FMAC6 soap_new_tree__findServiceDataResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__findServiceDataResponse(struct soap*, tree__findServiceDataResponse*);
SOAP_FMAC5 tree__findServiceDataResponse * SOAP_FMAC6 soap_instantiate_tree__findServiceDataResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__getCheckPointDataResponse
#define SOAP_TYPE_tree__getCheckPointDataResponse (36)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getCheckPointDataResponse(struct soap*, const char*, int, const tree__getCheckPointDataResponse *, const char*);
SOAP_FMAC3 tree__getCheckPointDataResponse * SOAP_FMAC4 soap_get_tree__getCheckPointDataResponse(struct soap*, tree__getCheckPointDataResponse *, const char*, const char*);
SOAP_FMAC3 tree__getCheckPointDataResponse * SOAP_FMAC4 soap_in_tree__getCheckPointDataResponse(struct soap*, const char*, tree__getCheckPointDataResponse *, const char*);

SOAP_FMAC5 tree__getCheckPointDataResponse * SOAP_FMAC6 soap_new_tree__getCheckPointDataResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__getCheckPointDataResponse(struct soap*, tree__getCheckPointDataResponse*);
SOAP_FMAC5 tree__getCheckPointDataResponse * SOAP_FMAC6 soap_instantiate_tree__getCheckPointDataResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__addNodeResponse
#define SOAP_TYPE_tree__addNodeResponse (35)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__addNodeResponse(struct soap*, const char*, int, const tree__addNodeResponse *, const char*);
SOAP_FMAC3 tree__addNodeResponse * SOAP_FMAC4 soap_get_tree__addNodeResponse(struct soap*, tree__addNodeResponse *, const char*, const char*);
SOAP_FMAC3 tree__addNodeResponse * SOAP_FMAC4 soap_in_tree__addNodeResponse(struct soap*, const char*, tree__addNodeResponse *, const char*);

SOAP_FMAC5 tree__addNodeResponse * SOAP_FMAC6 soap_new_tree__addNodeResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__addNodeResponse(struct soap*, tree__addNodeResponse*);
SOAP_FMAC5 tree__addNodeResponse * SOAP_FMAC6 soap_instantiate_tree__addNodeResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__requestTerminationAfterResponse
#define SOAP_TYPE_tree__requestTerminationAfterResponse (34)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__requestTerminationAfterResponse(struct soap*, const char*, int, const tree__requestTerminationAfterResponse *, const char*);
SOAP_FMAC3 tree__requestTerminationAfterResponse * SOAP_FMAC4 soap_get_tree__requestTerminationAfterResponse(struct soap*, tree__requestTerminationAfterResponse *, const char*, const char*);
SOAP_FMAC3 tree__requestTerminationAfterResponse * SOAP_FMAC4 soap_in_tree__requestTerminationAfterResponse(struct soap*, const char*, tree__requestTerminationAfterResponse *, const char*);

SOAP_FMAC5 tree__requestTerminationAfterResponse * SOAP_FMAC6 soap_new_tree__requestTerminationAfterResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__requestTerminationAfterResponse(struct soap*, tree__requestTerminationAfterResponse*);
SOAP_FMAC5 tree__requestTerminationAfterResponse * SOAP_FMAC6 soap_instantiate_tree__requestTerminationAfterResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tree__getParentNodeResponse
#define SOAP_TYPE_tree__getParentNodeResponse (33)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getParentNodeResponse(struct soap*, const char*, int, const tree__getParentNodeResponse *, const char*);
SOAP_FMAC3 tree__getParentNodeResponse * SOAP_FMAC4 soap_get_tree__getParentNodeResponse(struct soap*, tree__getParentNodeResponse *, const char*, const char*);
SOAP_FMAC3 tree__getParentNodeResponse * SOAP_FMAC4 soap_in_tree__getParentNodeResponse(struct soap*, const char*, tree__getParentNodeResponse *, const char*);

SOAP_FMAC5 tree__getParentNodeResponse * SOAP_FMAC6 soap_new_tree__getParentNodeResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_tree__getParentNodeResponse(struct soap*, tree__getParentNodeResponse*);
SOAP_FMAC5 tree__getParentNodeResponse * SOAP_FMAC6 soap_instantiate_tree__getParentNodeResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_fact__destroyResponse
#define SOAP_TYPE_fact__destroyResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__destroyResponse(struct soap*, const char*, int, const fact__destroyResponse *, const char*);
SOAP_FMAC3 fact__destroyResponse * SOAP_FMAC4 soap_get_fact__destroyResponse(struct soap*, fact__destroyResponse *, const char*, const char*);
SOAP_FMAC3 fact__destroyResponse * SOAP_FMAC4 soap_in_fact__destroyResponse(struct soap*, const char*, fact__destroyResponse *, const char*);

SOAP_FMAC5 fact__destroyResponse * SOAP_FMAC6 soap_new_fact__destroyResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fact__destroyResponse(struct soap*, fact__destroyResponse*);
SOAP_FMAC5 fact__destroyResponse * SOAP_FMAC6 soap_instantiate_fact__destroyResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_fact__requestTerminationAfterResponse
#define SOAP_TYPE_fact__requestTerminationAfterResponse (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__requestTerminationAfterResponse(struct soap*, const char*, int, const fact__requestTerminationAfterResponse *, const char*);
SOAP_FMAC3 fact__requestTerminationAfterResponse * SOAP_FMAC4 soap_get_fact__requestTerminationAfterResponse(struct soap*, fact__requestTerminationAfterResponse *, const char*, const char*);
SOAP_FMAC3 fact__requestTerminationAfterResponse * SOAP_FMAC4 soap_in_fact__requestTerminationAfterResponse(struct soap*, const char*, fact__requestTerminationAfterResponse *, const char*);

SOAP_FMAC5 fact__requestTerminationAfterResponse * SOAP_FMAC6 soap_new_fact__requestTerminationAfterResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fact__requestTerminationAfterResponse(struct soap*, fact__requestTerminationAfterResponse*);
SOAP_FMAC5 fact__requestTerminationAfterResponse * SOAP_FMAC6 soap_instantiate_fact__requestTerminationAfterResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_fact__createNewTreeResponse
#define SOAP_TYPE_fact__createNewTreeResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__createNewTreeResponse(struct soap*, const char*, int, const fact__createNewTreeResponse *, const char*);
SOAP_FMAC3 fact__createNewTreeResponse * SOAP_FMAC4 soap_get_fact__createNewTreeResponse(struct soap*, fact__createNewTreeResponse *, const char*, const char*);
SOAP_FMAC3 fact__createNewTreeResponse * SOAP_FMAC4 soap_in_fact__createNewTreeResponse(struct soap*, const char*, fact__createNewTreeResponse *, const char*);

SOAP_FMAC5 fact__createNewTreeResponse * SOAP_FMAC6 soap_new_fact__createNewTreeResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fact__createNewTreeResponse(struct soap*, fact__createNewTreeResponse*);
SOAP_FMAC5 fact__createNewTreeResponse * SOAP_FMAC6 soap_instantiate_fact__createNewTreeResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_fact__getActiveTreesResponse
#define SOAP_TYPE_fact__getActiveTreesResponse (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__getActiveTreesResponse(struct soap*, const char*, int, const fact__getActiveTreesResponse *, const char*);
SOAP_FMAC3 fact__getActiveTreesResponse * SOAP_FMAC4 soap_get_fact__getActiveTreesResponse(struct soap*, fact__getActiveTreesResponse *, const char*, const char*);
SOAP_FMAC3 fact__getActiveTreesResponse * SOAP_FMAC4 soap_in_fact__getActiveTreesResponse(struct soap*, const char*, fact__getActiveTreesResponse *, const char*);

SOAP_FMAC5 fact__getActiveTreesResponse * SOAP_FMAC6 soap_new_fact__getActiveTreesResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fact__getActiveTreesResponse(struct soap*, fact__getActiveTreesResponse*);
SOAP_FMAC5 fact__getActiveTreesResponse * SOAP_FMAC6 soap_instantiate_fact__getActiveTreesResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_fact__findByHandleResponse
#define SOAP_TYPE_fact__findByHandleResponse (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__findByHandleResponse(struct soap*, const char*, int, const fact__findByHandleResponse *, const char*);
SOAP_FMAC3 fact__findByHandleResponse * SOAP_FMAC4 soap_get_fact__findByHandleResponse(struct soap*, fact__findByHandleResponse *, const char*, const char*);
SOAP_FMAC3 fact__findByHandleResponse * SOAP_FMAC4 soap_in_fact__findByHandleResponse(struct soap*, const char*, fact__findByHandleResponse *, const char*);

SOAP_FMAC5 fact__findByHandleResponse * SOAP_FMAC6 soap_new_fact__findByHandleResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fact__findByHandleResponse(struct soap*, fact__findByHandleResponse*);
SOAP_FMAC5 fact__findByHandleResponse * SOAP_FMAC6 soap_instantiate_fact__findByHandleResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_fact__findServiceDataResponse
#define SOAP_TYPE_fact__findServiceDataResponse (6)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__findServiceDataResponse(struct soap*, const char*, int, const fact__findServiceDataResponse *, const char*);
SOAP_FMAC3 fact__findServiceDataResponse * SOAP_FMAC4 soap_get_fact__findServiceDataResponse(struct soap*, fact__findServiceDataResponse *, const char*, const char*);
SOAP_FMAC3 fact__findServiceDataResponse * SOAP_FMAC4 soap_in_fact__findServiceDataResponse(struct soap*, const char*, fact__findServiceDataResponse *, const char*);

SOAP_FMAC5 fact__findServiceDataResponse * SOAP_FMAC6 soap_new_fact__findServiceDataResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fact__findServiceDataResponse(struct soap*, fact__findServiceDataResponse*);
SOAP_FMAC5 fact__findServiceDataResponse * SOAP_FMAC6 soap_instantiate_fact__findServiceDataResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_fact__requestTerminationBeforeResponse
#define SOAP_TYPE_fact__requestTerminationBeforeResponse (5)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__requestTerminationBeforeResponse(struct soap*, const char*, int, const fact__requestTerminationBeforeResponse *, const char*);
SOAP_FMAC3 fact__requestTerminationBeforeResponse * SOAP_FMAC4 soap_get_fact__requestTerminationBeforeResponse(struct soap*, fact__requestTerminationBeforeResponse *, const char*, const char*);
SOAP_FMAC3 fact__requestTerminationBeforeResponse * SOAP_FMAC4 soap_in_fact__requestTerminationBeforeResponse(struct soap*, const char*, fact__requestTerminationBeforeResponse *, const char*);

SOAP_FMAC5 fact__requestTerminationBeforeResponse * SOAP_FMAC6 soap_new_fact__requestTerminationBeforeResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fact__requestTerminationBeforeResponse(struct soap*, fact__requestTerminationBeforeResponse*);
SOAP_FMAC5 fact__requestTerminationBeforeResponse * SOAP_FMAC6 soap_instantiate_fact__requestTerminationBeforeResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_tree__addNode
#define SOAP_TYPE_tree__addNode (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__addNode(struct soap*, struct tree__addNode const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__addNode(struct soap*, const struct tree__addNode *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__addNode(struct soap*, struct tree__addNode *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__addNode(struct soap*, struct tree__addNode *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__addNode(struct soap*, const char*, int, const struct tree__addNode *, const char*);
SOAP_FMAC3 struct tree__addNode * SOAP_FMAC4 soap_get_tree__addNode(struct soap*, struct tree__addNode *, const char*, const char*);
SOAP_FMAC3 struct tree__addNode * SOAP_FMAC4 soap_in_tree__addNode(struct soap*, const char*, struct tree__addNode *, const char*);

#ifndef SOAP_TYPE_tree__getParentNode
#define SOAP_TYPE_tree__getParentNode (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__getParentNode(struct soap*, struct tree__getParentNode const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__getParentNode(struct soap*, const struct tree__getParentNode *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__getParentNode(struct soap*, struct tree__getParentNode *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__getParentNode(struct soap*, struct tree__getParentNode *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getParentNode(struct soap*, const char*, int, const struct tree__getParentNode *, const char*);
SOAP_FMAC3 struct tree__getParentNode * SOAP_FMAC4 soap_get_tree__getParentNode(struct soap*, struct tree__getParentNode *, const char*, const char*);
SOAP_FMAC3 struct tree__getParentNode * SOAP_FMAC4 soap_in_tree__getParentNode(struct soap*, const char*, struct tree__getParentNode *, const char*);

#ifndef SOAP_TYPE_tree__getCheckPointData
#define SOAP_TYPE_tree__getCheckPointData (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__getCheckPointData(struct soap*, struct tree__getCheckPointData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__getCheckPointData(struct soap*, const struct tree__getCheckPointData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__getCheckPointData(struct soap*, struct tree__getCheckPointData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__getCheckPointData(struct soap*, struct tree__getCheckPointData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getCheckPointData(struct soap*, const char*, int, const struct tree__getCheckPointData *, const char*);
SOAP_FMAC3 struct tree__getCheckPointData * SOAP_FMAC4 soap_get_tree__getCheckPointData(struct soap*, struct tree__getCheckPointData *, const char*, const char*);
SOAP_FMAC3 struct tree__getCheckPointData * SOAP_FMAC4 soap_in_tree__getCheckPointData(struct soap*, const char*, struct tree__getCheckPointData *, const char*);

#ifndef SOAP_TYPE_tree__requestTerminationBefore
#define SOAP_TYPE_tree__requestTerminationBefore (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__requestTerminationBefore(struct soap*, struct tree__requestTerminationBefore const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__requestTerminationBefore(struct soap*, const struct tree__requestTerminationBefore *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__requestTerminationBefore(struct soap*, struct tree__requestTerminationBefore *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__requestTerminationBefore(struct soap*, struct tree__requestTerminationBefore *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__requestTerminationBefore(struct soap*, const char*, int, const struct tree__requestTerminationBefore *, const char*);
SOAP_FMAC3 struct tree__requestTerminationBefore * SOAP_FMAC4 soap_get_tree__requestTerminationBefore(struct soap*, struct tree__requestTerminationBefore *, const char*, const char*);
SOAP_FMAC3 struct tree__requestTerminationBefore * SOAP_FMAC4 soap_in_tree__requestTerminationBefore(struct soap*, const char*, struct tree__requestTerminationBefore *, const char*);

#ifndef SOAP_TYPE_tree__getSteeringCommands
#define SOAP_TYPE_tree__getSteeringCommands (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__getSteeringCommands(struct soap*, struct tree__getSteeringCommands const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__getSteeringCommands(struct soap*, const struct tree__getSteeringCommands *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__getSteeringCommands(struct soap*, struct tree__getSteeringCommands *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__getSteeringCommands(struct soap*, struct tree__getSteeringCommands *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getSteeringCommands(struct soap*, const char*, int, const struct tree__getSteeringCommands *, const char*);
SOAP_FMAC3 struct tree__getSteeringCommands * SOAP_FMAC4 soap_get_tree__getSteeringCommands(struct soap*, struct tree__getSteeringCommands *, const char*, const char*);
SOAP_FMAC3 struct tree__getSteeringCommands * SOAP_FMAC4 soap_in_tree__getSteeringCommands(struct soap*, const char*, struct tree__getSteeringCommands *, const char*);

#ifndef SOAP_TYPE_tree__destroy
#define SOAP_TYPE_tree__destroy (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__destroy(struct soap*, struct tree__destroy const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__destroy(struct soap*, const struct tree__destroy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__destroy(struct soap*, struct tree__destroy *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__destroy(struct soap*, struct tree__destroy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__destroy(struct soap*, const char*, int, const struct tree__destroy *, const char*);
SOAP_FMAC3 struct tree__destroy * SOAP_FMAC4 soap_get_tree__destroy(struct soap*, struct tree__destroy *, const char*, const char*);
SOAP_FMAC3 struct tree__destroy * SOAP_FMAC4 soap_in_tree__destroy(struct soap*, const char*, struct tree__destroy *, const char*);

#ifndef SOAP_TYPE_tree__setCheckPointData
#define SOAP_TYPE_tree__setCheckPointData (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__setCheckPointData(struct soap*, struct tree__setCheckPointData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__setCheckPointData(struct soap*, const struct tree__setCheckPointData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__setCheckPointData(struct soap*, struct tree__setCheckPointData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__setCheckPointData(struct soap*, struct tree__setCheckPointData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__setCheckPointData(struct soap*, const char*, int, const struct tree__setCheckPointData *, const char*);
SOAP_FMAC3 struct tree__setCheckPointData * SOAP_FMAC4 soap_get_tree__setCheckPointData(struct soap*, struct tree__setCheckPointData *, const char*, const char*);
SOAP_FMAC3 struct tree__setCheckPointData * SOAP_FMAC4 soap_in_tree__setCheckPointData(struct soap*, const char*, struct tree__setCheckPointData *, const char*);

#ifndef SOAP_TYPE_tree__findServiceData
#define SOAP_TYPE_tree__findServiceData (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__findServiceData(struct soap*, struct tree__findServiceData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__findServiceData(struct soap*, const struct tree__findServiceData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__findServiceData(struct soap*, struct tree__findServiceData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__findServiceData(struct soap*, struct tree__findServiceData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__findServiceData(struct soap*, const char*, int, const struct tree__findServiceData *, const char*);
SOAP_FMAC3 struct tree__findServiceData * SOAP_FMAC4 soap_get_tree__findServiceData(struct soap*, struct tree__findServiceData *, const char*, const char*);
SOAP_FMAC3 struct tree__findServiceData * SOAP_FMAC4 soap_in_tree__findServiceData(struct soap*, const char*, struct tree__findServiceData *, const char*);

#ifndef SOAP_TYPE_tree__getInputFile
#define SOAP_TYPE_tree__getInputFile (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__getInputFile(struct soap*, struct tree__getInputFile const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__getInputFile(struct soap*, const struct tree__getInputFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__getInputFile(struct soap*, struct tree__getInputFile *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__getInputFile(struct soap*, struct tree__getInputFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getInputFile(struct soap*, const char*, int, const struct tree__getInputFile *, const char*);
SOAP_FMAC3 struct tree__getInputFile * SOAP_FMAC4 soap_get_tree__getInputFile(struct soap*, struct tree__getInputFile *, const char*, const char*);
SOAP_FMAC3 struct tree__getInputFile * SOAP_FMAC4 soap_in_tree__getInputFile(struct soap*, const char*, struct tree__getInputFile *, const char*);

#ifndef SOAP_TYPE_tree__getChildNodes
#define SOAP_TYPE_tree__getChildNodes (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__getChildNodes(struct soap*, struct tree__getChildNodes const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__getChildNodes(struct soap*, const struct tree__getChildNodes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__getChildNodes(struct soap*, struct tree__getChildNodes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__getChildNodes(struct soap*, struct tree__getChildNodes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__getChildNodes(struct soap*, const char*, int, const struct tree__getChildNodes *, const char*);
SOAP_FMAC3 struct tree__getChildNodes * SOAP_FMAC4 soap_get_tree__getChildNodes(struct soap*, struct tree__getChildNodes *, const char*, const char*);
SOAP_FMAC3 struct tree__getChildNodes * SOAP_FMAC4 soap_in_tree__getChildNodes(struct soap*, const char*, struct tree__getChildNodes *, const char*);

#ifndef SOAP_TYPE_tree__requestTerminationAfter
#define SOAP_TYPE_tree__requestTerminationAfter (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tree__requestTerminationAfter(struct soap*, struct tree__requestTerminationAfter const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tree__requestTerminationAfter(struct soap*, const struct tree__requestTerminationAfter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tree__requestTerminationAfter(struct soap*, struct tree__requestTerminationAfter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tree__requestTerminationAfter(struct soap*, struct tree__requestTerminationAfter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tree__requestTerminationAfter(struct soap*, const char*, int, const struct tree__requestTerminationAfter *, const char*);
SOAP_FMAC3 struct tree__requestTerminationAfter * SOAP_FMAC4 soap_get_tree__requestTerminationAfter(struct soap*, struct tree__requestTerminationAfter *, const char*, const char*);
SOAP_FMAC3 struct tree__requestTerminationAfter * SOAP_FMAC4 soap_in_tree__requestTerminationAfter(struct soap*, const char*, struct tree__requestTerminationAfter *, const char*);

#ifndef SOAP_TYPE_fact__requestTerminationAfter
#define SOAP_TYPE_fact__requestTerminationAfter (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fact__requestTerminationAfter(struct soap*, struct fact__requestTerminationAfter const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_fact__requestTerminationAfter(struct soap*, const struct fact__requestTerminationAfter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fact__requestTerminationAfter(struct soap*, struct fact__requestTerminationAfter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fact__requestTerminationAfter(struct soap*, struct fact__requestTerminationAfter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__requestTerminationAfter(struct soap*, const char*, int, const struct fact__requestTerminationAfter *, const char*);
SOAP_FMAC3 struct fact__requestTerminationAfter * SOAP_FMAC4 soap_get_fact__requestTerminationAfter(struct soap*, struct fact__requestTerminationAfter *, const char*, const char*);
SOAP_FMAC3 struct fact__requestTerminationAfter * SOAP_FMAC4 soap_in_fact__requestTerminationAfter(struct soap*, const char*, struct fact__requestTerminationAfter *, const char*);

#ifndef SOAP_TYPE_fact__requestTerminationBefore
#define SOAP_TYPE_fact__requestTerminationBefore (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fact__requestTerminationBefore(struct soap*, struct fact__requestTerminationBefore const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_fact__requestTerminationBefore(struct soap*, const struct fact__requestTerminationBefore *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fact__requestTerminationBefore(struct soap*, struct fact__requestTerminationBefore *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fact__requestTerminationBefore(struct soap*, struct fact__requestTerminationBefore *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__requestTerminationBefore(struct soap*, const char*, int, const struct fact__requestTerminationBefore *, const char*);
SOAP_FMAC3 struct fact__requestTerminationBefore * SOAP_FMAC4 soap_get_fact__requestTerminationBefore(struct soap*, struct fact__requestTerminationBefore *, const char*, const char*);
SOAP_FMAC3 struct fact__requestTerminationBefore * SOAP_FMAC4 soap_in_fact__requestTerminationBefore(struct soap*, const char*, struct fact__requestTerminationBefore *, const char*);

#ifndef SOAP_TYPE_fact__getActiveTrees
#define SOAP_TYPE_fact__getActiveTrees (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fact__getActiveTrees(struct soap*, struct fact__getActiveTrees const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_fact__getActiveTrees(struct soap*, const struct fact__getActiveTrees *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fact__getActiveTrees(struct soap*, struct fact__getActiveTrees *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fact__getActiveTrees(struct soap*, struct fact__getActiveTrees *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__getActiveTrees(struct soap*, const char*, int, const struct fact__getActiveTrees *, const char*);
SOAP_FMAC3 struct fact__getActiveTrees * SOAP_FMAC4 soap_get_fact__getActiveTrees(struct soap*, struct fact__getActiveTrees *, const char*, const char*);
SOAP_FMAC3 struct fact__getActiveTrees * SOAP_FMAC4 soap_in_fact__getActiveTrees(struct soap*, const char*, struct fact__getActiveTrees *, const char*);

#ifndef SOAP_TYPE_fact__findServiceData
#define SOAP_TYPE_fact__findServiceData (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fact__findServiceData(struct soap*, struct fact__findServiceData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_fact__findServiceData(struct soap*, const struct fact__findServiceData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fact__findServiceData(struct soap*, struct fact__findServiceData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fact__findServiceData(struct soap*, struct fact__findServiceData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__findServiceData(struct soap*, const char*, int, const struct fact__findServiceData *, const char*);
SOAP_FMAC3 struct fact__findServiceData * SOAP_FMAC4 soap_get_fact__findServiceData(struct soap*, struct fact__findServiceData *, const char*, const char*);
SOAP_FMAC3 struct fact__findServiceData * SOAP_FMAC4 soap_in_fact__findServiceData(struct soap*, const char*, struct fact__findServiceData *, const char*);

#ifndef SOAP_TYPE_fact__destroy
#define SOAP_TYPE_fact__destroy (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fact__destroy(struct soap*, struct fact__destroy const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_fact__destroy(struct soap*, const struct fact__destroy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fact__destroy(struct soap*, struct fact__destroy *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fact__destroy(struct soap*, struct fact__destroy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__destroy(struct soap*, const char*, int, const struct fact__destroy *, const char*);
SOAP_FMAC3 struct fact__destroy * SOAP_FMAC4 soap_get_fact__destroy(struct soap*, struct fact__destroy *, const char*, const char*);
SOAP_FMAC3 struct fact__destroy * SOAP_FMAC4 soap_in_fact__destroy(struct soap*, const char*, struct fact__destroy *, const char*);

#ifndef SOAP_TYPE_fact__findByHandle
#define SOAP_TYPE_fact__findByHandle (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fact__findByHandle(struct soap*, struct fact__findByHandle const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_fact__findByHandle(struct soap*, const struct fact__findByHandle *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fact__findByHandle(struct soap*, struct fact__findByHandle *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fact__findByHandle(struct soap*, struct fact__findByHandle *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__findByHandle(struct soap*, const char*, int, const struct fact__findByHandle *, const char*);
SOAP_FMAC3 struct fact__findByHandle * SOAP_FMAC4 soap_get_fact__findByHandle(struct soap*, struct fact__findByHandle *, const char*, const char*);
SOAP_FMAC3 struct fact__findByHandle * SOAP_FMAC4 soap_in_fact__findByHandle(struct soap*, const char*, struct fact__findByHandle *, const char*);

#ifndef SOAP_TYPE_fact__createNewTree
#define SOAP_TYPE_fact__createNewTree (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fact__createNewTree(struct soap*, struct fact__createNewTree const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_fact__createNewTree(struct soap*, const struct fact__createNewTree *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fact__createNewTree(struct soap*, struct fact__createNewTree *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fact__createNewTree(struct soap*, struct fact__createNewTree *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fact__createNewTree(struct soap*, const char*, int, const struct fact__createNewTree *, const char*);
SOAP_FMAC3 struct fact__createNewTree * SOAP_FMAC4 soap_get_fact__createNewTree(struct soap*, struct fact__createNewTree *, const char*, const char*);
SOAP_FMAC3 struct fact__createNewTree * SOAP_FMAC4 soap_in_fact__createNewTree(struct soap*, const char*, struct fact__createNewTree *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTotree__addNodeResponse
#define SOAP_TYPE_PointerTotree__addNodeResponse (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__addNodeResponse(struct soap*, tree__addNodeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__addNodeResponse(struct soap*, tree__addNodeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__addNodeResponse(struct soap*, tree__addNodeResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__addNodeResponse(struct soap*, tree__addNodeResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__addNodeResponse(struct soap*, const char *, int, tree__addNodeResponse *const*, const char *);
SOAP_FMAC3 tree__addNodeResponse ** SOAP_FMAC4 soap_get_PointerTotree__addNodeResponse(struct soap*, tree__addNodeResponse **, const char*, const char*);
SOAP_FMAC3 tree__addNodeResponse ** SOAP_FMAC4 soap_in_PointerTotree__addNodeResponse(struct soap*, const char*, tree__addNodeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__getParentNodeResponse
#define SOAP_TYPE_PointerTotree__getParentNodeResponse (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__getParentNodeResponse(struct soap*, tree__getParentNodeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__getParentNodeResponse(struct soap*, tree__getParentNodeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__getParentNodeResponse(struct soap*, tree__getParentNodeResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__getParentNodeResponse(struct soap*, tree__getParentNodeResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__getParentNodeResponse(struct soap*, const char *, int, tree__getParentNodeResponse *const*, const char *);
SOAP_FMAC3 tree__getParentNodeResponse ** SOAP_FMAC4 soap_get_PointerTotree__getParentNodeResponse(struct soap*, tree__getParentNodeResponse **, const char*, const char*);
SOAP_FMAC3 tree__getParentNodeResponse ** SOAP_FMAC4 soap_in_PointerTotree__getParentNodeResponse(struct soap*, const char*, tree__getParentNodeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__getCheckPointDataResponse
#define SOAP_TYPE_PointerTotree__getCheckPointDataResponse (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__getCheckPointDataResponse(struct soap*, tree__getCheckPointDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__getCheckPointDataResponse(struct soap*, tree__getCheckPointDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__getCheckPointDataResponse(struct soap*, tree__getCheckPointDataResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__getCheckPointDataResponse(struct soap*, tree__getCheckPointDataResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__getCheckPointDataResponse(struct soap*, const char *, int, tree__getCheckPointDataResponse *const*, const char *);
SOAP_FMAC3 tree__getCheckPointDataResponse ** SOAP_FMAC4 soap_get_PointerTotree__getCheckPointDataResponse(struct soap*, tree__getCheckPointDataResponse **, const char*, const char*);
SOAP_FMAC3 tree__getCheckPointDataResponse ** SOAP_FMAC4 soap_in_PointerTotree__getCheckPointDataResponse(struct soap*, const char*, tree__getCheckPointDataResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__requestTerminationBeforeResponse
#define SOAP_TYPE_PointerTotree__requestTerminationBeforeResponse (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__requestTerminationBeforeResponse(struct soap*, tree__requestTerminationBeforeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__requestTerminationBeforeResponse(struct soap*, tree__requestTerminationBeforeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__requestTerminationBeforeResponse(struct soap*, tree__requestTerminationBeforeResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__requestTerminationBeforeResponse(struct soap*, tree__requestTerminationBeforeResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__requestTerminationBeforeResponse(struct soap*, const char *, int, tree__requestTerminationBeforeResponse *const*, const char *);
SOAP_FMAC3 tree__requestTerminationBeforeResponse ** SOAP_FMAC4 soap_get_PointerTotree__requestTerminationBeforeResponse(struct soap*, tree__requestTerminationBeforeResponse **, const char*, const char*);
SOAP_FMAC3 tree__requestTerminationBeforeResponse ** SOAP_FMAC4 soap_in_PointerTotree__requestTerminationBeforeResponse(struct soap*, const char*, tree__requestTerminationBeforeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__getSteeringCommandsResponse
#define SOAP_TYPE_PointerTotree__getSteeringCommandsResponse (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__getSteeringCommandsResponse(struct soap*, tree__getSteeringCommandsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__getSteeringCommandsResponse(struct soap*, tree__getSteeringCommandsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__getSteeringCommandsResponse(struct soap*, tree__getSteeringCommandsResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__getSteeringCommandsResponse(struct soap*, tree__getSteeringCommandsResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__getSteeringCommandsResponse(struct soap*, const char *, int, tree__getSteeringCommandsResponse *const*, const char *);
SOAP_FMAC3 tree__getSteeringCommandsResponse ** SOAP_FMAC4 soap_get_PointerTotree__getSteeringCommandsResponse(struct soap*, tree__getSteeringCommandsResponse **, const char*, const char*);
SOAP_FMAC3 tree__getSteeringCommandsResponse ** SOAP_FMAC4 soap_in_PointerTotree__getSteeringCommandsResponse(struct soap*, const char*, tree__getSteeringCommandsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__destroyResponse
#define SOAP_TYPE_PointerTotree__destroyResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__destroyResponse(struct soap*, tree__destroyResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__destroyResponse(struct soap*, tree__destroyResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__destroyResponse(struct soap*, tree__destroyResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__destroyResponse(struct soap*, tree__destroyResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__destroyResponse(struct soap*, const char *, int, tree__destroyResponse *const*, const char *);
SOAP_FMAC3 tree__destroyResponse ** SOAP_FMAC4 soap_get_PointerTotree__destroyResponse(struct soap*, tree__destroyResponse **, const char*, const char*);
SOAP_FMAC3 tree__destroyResponse ** SOAP_FMAC4 soap_in_PointerTotree__destroyResponse(struct soap*, const char*, tree__destroyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__setCheckPointDataResponse
#define SOAP_TYPE_PointerTotree__setCheckPointDataResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__setCheckPointDataResponse(struct soap*, tree__setCheckPointDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__setCheckPointDataResponse(struct soap*, tree__setCheckPointDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__setCheckPointDataResponse(struct soap*, tree__setCheckPointDataResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__setCheckPointDataResponse(struct soap*, tree__setCheckPointDataResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__setCheckPointDataResponse(struct soap*, const char *, int, tree__setCheckPointDataResponse *const*, const char *);
SOAP_FMAC3 tree__setCheckPointDataResponse ** SOAP_FMAC4 soap_get_PointerTotree__setCheckPointDataResponse(struct soap*, tree__setCheckPointDataResponse **, const char*, const char*);
SOAP_FMAC3 tree__setCheckPointDataResponse ** SOAP_FMAC4 soap_in_PointerTotree__setCheckPointDataResponse(struct soap*, const char*, tree__setCheckPointDataResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__findServiceDataResponse
#define SOAP_TYPE_PointerTotree__findServiceDataResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__findServiceDataResponse(struct soap*, tree__findServiceDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__findServiceDataResponse(struct soap*, tree__findServiceDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__findServiceDataResponse(struct soap*, tree__findServiceDataResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__findServiceDataResponse(struct soap*, tree__findServiceDataResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__findServiceDataResponse(struct soap*, const char *, int, tree__findServiceDataResponse *const*, const char *);
SOAP_FMAC3 tree__findServiceDataResponse ** SOAP_FMAC4 soap_get_PointerTotree__findServiceDataResponse(struct soap*, tree__findServiceDataResponse **, const char*, const char*);
SOAP_FMAC3 tree__findServiceDataResponse ** SOAP_FMAC4 soap_in_PointerTotree__findServiceDataResponse(struct soap*, const char*, tree__findServiceDataResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__getInputFileResponse
#define SOAP_TYPE_PointerTotree__getInputFileResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__getInputFileResponse(struct soap*, tree__getInputFileResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__getInputFileResponse(struct soap*, tree__getInputFileResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__getInputFileResponse(struct soap*, tree__getInputFileResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__getInputFileResponse(struct soap*, tree__getInputFileResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__getInputFileResponse(struct soap*, const char *, int, tree__getInputFileResponse *const*, const char *);
SOAP_FMAC3 tree__getInputFileResponse ** SOAP_FMAC4 soap_get_PointerTotree__getInputFileResponse(struct soap*, tree__getInputFileResponse **, const char*, const char*);
SOAP_FMAC3 tree__getInputFileResponse ** SOAP_FMAC4 soap_in_PointerTotree__getInputFileResponse(struct soap*, const char*, tree__getInputFileResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__getChildNodesResponse
#define SOAP_TYPE_PointerTotree__getChildNodesResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__getChildNodesResponse(struct soap*, tree__getChildNodesResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__getChildNodesResponse(struct soap*, tree__getChildNodesResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__getChildNodesResponse(struct soap*, tree__getChildNodesResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__getChildNodesResponse(struct soap*, tree__getChildNodesResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__getChildNodesResponse(struct soap*, const char *, int, tree__getChildNodesResponse *const*, const char *);
SOAP_FMAC3 tree__getChildNodesResponse ** SOAP_FMAC4 soap_get_PointerTotree__getChildNodesResponse(struct soap*, tree__getChildNodesResponse **, const char*, const char*);
SOAP_FMAC3 tree__getChildNodesResponse ** SOAP_FMAC4 soap_in_PointerTotree__getChildNodesResponse(struct soap*, const char*, tree__getChildNodesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotree__requestTerminationAfterResponse
#define SOAP_TYPE_PointerTotree__requestTerminationAfterResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotree__requestTerminationAfterResponse(struct soap*, tree__requestTerminationAfterResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotree__requestTerminationAfterResponse(struct soap*, tree__requestTerminationAfterResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotree__requestTerminationAfterResponse(struct soap*, tree__requestTerminationAfterResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotree__requestTerminationAfterResponse(struct soap*, tree__requestTerminationAfterResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotree__requestTerminationAfterResponse(struct soap*, const char *, int, tree__requestTerminationAfterResponse *const*, const char *);
SOAP_FMAC3 tree__requestTerminationAfterResponse ** SOAP_FMAC4 soap_get_PointerTotree__requestTerminationAfterResponse(struct soap*, tree__requestTerminationAfterResponse **, const char*, const char*);
SOAP_FMAC3 tree__requestTerminationAfterResponse ** SOAP_FMAC4 soap_in_PointerTotree__requestTerminationAfterResponse(struct soap*, const char*, tree__requestTerminationAfterResponse **, const char*);

#ifndef SOAP_TYPE_PointerTofact__requestTerminationAfterResponse
#define SOAP_TYPE_PointerTofact__requestTerminationAfterResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofact__requestTerminationAfterResponse(struct soap*, fact__requestTerminationAfterResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofact__requestTerminationAfterResponse(struct soap*, fact__requestTerminationAfterResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofact__requestTerminationAfterResponse(struct soap*, fact__requestTerminationAfterResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofact__requestTerminationAfterResponse(struct soap*, fact__requestTerminationAfterResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofact__requestTerminationAfterResponse(struct soap*, const char *, int, fact__requestTerminationAfterResponse *const*, const char *);
SOAP_FMAC3 fact__requestTerminationAfterResponse ** SOAP_FMAC4 soap_get_PointerTofact__requestTerminationAfterResponse(struct soap*, fact__requestTerminationAfterResponse **, const char*, const char*);
SOAP_FMAC3 fact__requestTerminationAfterResponse ** SOAP_FMAC4 soap_in_PointerTofact__requestTerminationAfterResponse(struct soap*, const char*, fact__requestTerminationAfterResponse **, const char*);

#ifndef SOAP_TYPE_PointerTofact__requestTerminationBeforeResponse
#define SOAP_TYPE_PointerTofact__requestTerminationBeforeResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofact__requestTerminationBeforeResponse(struct soap*, fact__requestTerminationBeforeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofact__requestTerminationBeforeResponse(struct soap*, fact__requestTerminationBeforeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofact__requestTerminationBeforeResponse(struct soap*, fact__requestTerminationBeforeResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofact__requestTerminationBeforeResponse(struct soap*, fact__requestTerminationBeforeResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofact__requestTerminationBeforeResponse(struct soap*, const char *, int, fact__requestTerminationBeforeResponse *const*, const char *);
SOAP_FMAC3 fact__requestTerminationBeforeResponse ** SOAP_FMAC4 soap_get_PointerTofact__requestTerminationBeforeResponse(struct soap*, fact__requestTerminationBeforeResponse **, const char*, const char*);
SOAP_FMAC3 fact__requestTerminationBeforeResponse ** SOAP_FMAC4 soap_in_PointerTofact__requestTerminationBeforeResponse(struct soap*, const char*, fact__requestTerminationBeforeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTofact__getActiveTreesResponse
#define SOAP_TYPE_PointerTofact__getActiveTreesResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofact__getActiveTreesResponse(struct soap*, fact__getActiveTreesResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofact__getActiveTreesResponse(struct soap*, fact__getActiveTreesResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofact__getActiveTreesResponse(struct soap*, fact__getActiveTreesResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofact__getActiveTreesResponse(struct soap*, fact__getActiveTreesResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofact__getActiveTreesResponse(struct soap*, const char *, int, fact__getActiveTreesResponse *const*, const char *);
SOAP_FMAC3 fact__getActiveTreesResponse ** SOAP_FMAC4 soap_get_PointerTofact__getActiveTreesResponse(struct soap*, fact__getActiveTreesResponse **, const char*, const char*);
SOAP_FMAC3 fact__getActiveTreesResponse ** SOAP_FMAC4 soap_in_PointerTofact__getActiveTreesResponse(struct soap*, const char*, fact__getActiveTreesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTofact__findServiceDataResponse
#define SOAP_TYPE_PointerTofact__findServiceDataResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofact__findServiceDataResponse(struct soap*, fact__findServiceDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofact__findServiceDataResponse(struct soap*, fact__findServiceDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofact__findServiceDataResponse(struct soap*, fact__findServiceDataResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofact__findServiceDataResponse(struct soap*, fact__findServiceDataResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofact__findServiceDataResponse(struct soap*, const char *, int, fact__findServiceDataResponse *const*, const char *);
SOAP_FMAC3 fact__findServiceDataResponse ** SOAP_FMAC4 soap_get_PointerTofact__findServiceDataResponse(struct soap*, fact__findServiceDataResponse **, const char*, const char*);
SOAP_FMAC3 fact__findServiceDataResponse ** SOAP_FMAC4 soap_in_PointerTofact__findServiceDataResponse(struct soap*, const char*, fact__findServiceDataResponse **, const char*);

#ifndef SOAP_TYPE_PointerTofact__destroyResponse
#define SOAP_TYPE_PointerTofact__destroyResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofact__destroyResponse(struct soap*, fact__destroyResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofact__destroyResponse(struct soap*, fact__destroyResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofact__destroyResponse(struct soap*, fact__destroyResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofact__destroyResponse(struct soap*, fact__destroyResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofact__destroyResponse(struct soap*, const char *, int, fact__destroyResponse *const*, const char *);
SOAP_FMAC3 fact__destroyResponse ** SOAP_FMAC4 soap_get_PointerTofact__destroyResponse(struct soap*, fact__destroyResponse **, const char*, const char*);
SOAP_FMAC3 fact__destroyResponse ** SOAP_FMAC4 soap_in_PointerTofact__destroyResponse(struct soap*, const char*, fact__destroyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTofact__findByHandleResponse
#define SOAP_TYPE_PointerTofact__findByHandleResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofact__findByHandleResponse(struct soap*, fact__findByHandleResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofact__findByHandleResponse(struct soap*, fact__findByHandleResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofact__findByHandleResponse(struct soap*, fact__findByHandleResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofact__findByHandleResponse(struct soap*, fact__findByHandleResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofact__findByHandleResponse(struct soap*, const char *, int, fact__findByHandleResponse *const*, const char *);
SOAP_FMAC3 fact__findByHandleResponse ** SOAP_FMAC4 soap_get_PointerTofact__findByHandleResponse(struct soap*, fact__findByHandleResponse **, const char*, const char*);
SOAP_FMAC3 fact__findByHandleResponse ** SOAP_FMAC4 soap_in_PointerTofact__findByHandleResponse(struct soap*, const char*, fact__findByHandleResponse **, const char*);

#ifndef SOAP_TYPE_PointerTofact__createNewTreeResponse
#define SOAP_TYPE_PointerTofact__createNewTreeResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofact__createNewTreeResponse(struct soap*, fact__createNewTreeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofact__createNewTreeResponse(struct soap*, fact__createNewTreeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofact__createNewTreeResponse(struct soap*, fact__createNewTreeResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofact__createNewTreeResponse(struct soap*, fact__createNewTreeResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofact__createNewTreeResponse(struct soap*, const char *, int, fact__createNewTreeResponse *const*, const char *);
SOAP_FMAC3 fact__createNewTreeResponse ** SOAP_FMAC4 soap_get_PointerTofact__createNewTreeResponse(struct soap*, fact__createNewTreeResponse **, const char*, const char*);
SOAP_FMAC3 fact__createNewTreeResponse ** SOAP_FMAC4 soap_in_PointerTofact__createNewTreeResponse(struct soap*, const char*, fact__createNewTreeResponse **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(checkPointTree)

#endif

/* end of checkPointTreeH.h */
