#!/bin/sh
#----------------------------------------------------------------------
#  A shell script to launch the ReG steering system using COG kit,
#  globus or ssh.
#
#  (C) Copyright 2002, 2004, University of Manchester, United Kingdom,
#  all rights reserved.
#
#  This software is produced by the Supercomputing, Visualization and
#  e-Science Group, Manchester Computing, University of Manchester
#  as part of the RealityGrid project (http://www.realitygrid.org),
#  funded by the EPSRC under grants GR/R67699/01 and GR/R67699/02.
#
#  LICENCE TERMS
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS MATERIAL IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. THE ENTIRE RISK AS TO THE QUALITY
#  AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE
#  DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR
#  CORRECTION.
#
#  Author(s)......: <R. L. Pinning>
#  Modified:        <27.04.2004>
#
#------------------------------------------------------------------------


HOST=$1
JOBMGR=$2
REG_RSL=$3
USER=$4

case $ReG_LAUNCH in
    globus)
     echo "Using vanilla globus"
     $GLOBUS_LOCATION/bin/globusrun -b -s -r $HOST/$JOBMGR -f $REG_RSL
    ;;
    cog)
     echo "Using COG globus"
     $COG_INSTALL_PATH/bin/globusrun $5 -s -r $HOST/$JOBMGR -f $REG_RSL &
    ;;
    ssh)
        chmod a+x $REG_TMP_FILE
        scp $REG_TMP_FILE $USER@$HOST:$REG_TMP_FILE
        ssh -f $USER@$HOST $REG_TMP_FILE
    ;;
    *)
     echo "Usage: ./reg_globusrun  host jobmanager -f file.rsl"
    ;;
esac
