mConfigFileContent = QString("<?xml version=\"1.0\"?>\n"
"<launcher>\n"
" <settings>\n"
"   <scriptsDirectory value=\"/home/zzcguap/RealityGrid/reg_qt_launcher/scripts\"/>\n"
"   <scratchDirectory value=\"/home/zzcguap/RealityGrid/reg_qt_launcher/tmp\"/>\n"
"   <launchMethod value=\"globus\"/>\n"
"   <steerClientBinary value=\"/home/zzcguap/projects/reg_qt_steerer/steerer\"/>\n"
" </settings>\n"
" <GSHs>\n"
"  <topLevelRegistry value=\"http://yaffel.mvc.mcc.ac.uk:50000/Session/ServiceGroupRegistration/service?3893432997\"/>\n"
"  <checkPointTreeFactory value=\"http://vermont.mvc.mcc.ac.uk:50000/Session/RealityGridTree/factory\"/>\n"
"  <registryOfFactories value=\"\"/>\n"
"  <SGSFactory value=\"\"/>\n"
"  <SGS value=\"\"/>\n"
" </GSHs>\n"
" <containers>\n"
"  <container port=\"50000\">methuselah.mvc.mcc.ac.uk</container>\n"
"  <container port=\"50000\">garfield.mvc.mcc.ac.uk</container>\n"
"  <container port=\"50000\">yaffel.mvc.mcc.ac.uk</container>\n"
"  <container port=\"50122\">tg-login1.sdsc.edu</container>\n"
" </containers>\n"
" <targets>\n"
"  <machine name=\"localhost\" os=\"linux\" \n"
"           jobmanager=\"fork\" queue=\"none\"/>\n"
"  <machine name=\"bezier.man.ac.uk\" os=\"irix\" \n"
"           jobmanager=\"bezier.man.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
"  <machine name=\"grid-compute.oesc.ox.ac.uk\" os=\"linux\" \n"
"           jobmanager=\"grid-compute.oesc.ox.ac.uk/jobmanager-pbs\" queue=\"none\"/>\n"
"  <machine name=\"grid-compute.leeds.ac.uk\" os=\"linux\" \n"
"           jobmanager=\"grid-compute.leeds.ac.uk/jobmanager-pbs\" queue=\"none\"/>\n"
"  <machine name=\"grid-data.man.ac.uk\" os=\"linux\" \n"
"           jobmanager=\"grid-data.man.ac.uk/jobmanager-pbs\" queue=\"none\"/>\n"
"  <machine name=\"grid-data.rl.ac.uk\" os=\"linux\" \n"
"           jobmanager=\"grid-data.rl.ac.uk/jobmanager-pbs\" queue=\"none\"/>\n"
"  <machine name=\"dirac.chem.ucl.ac.uk\" os=\"irix\" \n"
"           jobmanager=\"dirac.chem.ucl.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
"  <machine name=\"tg-login.sdsc.teragrid.org\" os=\"linux\" \n"
"           jobmanager=\"tg-login.sdsc.teragrid.org/jobmanager-pbs\" queue=\"none\"/>\n"
"  <machine name=\"tg-login.ncsa.teragrid.org\" os=\"linux\" \n"
"           jobmanager=\"tg-login.ncsa.teragrid.org/jobmanager-pbs\" queue=\"none\"/>\n"
"  <machine name=\"lemieux.psc.edu\" os=\"TRU64\" \n"
"           jobmanager=\"tg-globus-submit.psc.edu/jobmanager-lemieux-pbs\" queue=\"escience\"/>\n"
"  <machine name=\"fermat.cfs.ac.uk\" os=\"irix\" \n"
"           jobmanager=\"wren.cfs.ac.uk/jobmanager-lsf-fermat\" queue=\"none\"/>\n"
"  <machine name=\"green.cfs.ac.uk\" os=\"irix\" \n"
"           jobmanager=\"wren.cfs.ac.uk/jobmanager-lsf-green\" queue=\"none\"/>\n"
"  <machine name=\"wren.cfs.ac.uk\" os=\"irix\" \n"
"           jobmanager=\"wren.cfs.ac.uk/jobmanager-lsf\" queue=\"none\"/>\n"
"  <machine name=\"login.hpcx.ac.uk\" os=\"aix\" \n"
"           jobmanager=\"login.hpcx.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
"  <machine name=\"booboo.mvc.mcc.ac.uk\" os=\"linux\" \n"
"           jobmanager=\"booboo.mvc.mcc.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
"  <machine name=\"yaffel.mvc.mcc.ac.uk\" os=\"linux\"\n"
"           jobmanager=\"yaffel.mvc.mcc.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
" </targets>\n"
" <vizTargets>\n"
"  <machine name=\"localhost\" os=\"linux\" \n"
"           jobmanager=\"fork\" queue=\"none\"/>\n"
"  <machine name=\"bezier.man.ac.uk\" os=\"irix\" \n"
"           jobmanager=\"bezier.man.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
"  <machine name=\"dirac.chem.ucl.ac.uk\" os=\"irix\" \n"
"           jobmanager=\"dirac.chem.ucl.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
"  <machine name=\"booboo.mvc.mcc.ac.uk\" os=\"linux\" \n"
"           jobmanager=\"booboo.mvc.mcc.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
"  <machine name=\"yaffel.mvc.mcc.ac.uk\" os=\"linux\" \n"
"           jobmanager=\"yaffel.mvc.mcc.ac.uk/jobmanager-fork\" queue=\"none\"/>\n"
" </vizTargets>\n"
" <applications>\n"
"  <application name=\"ReGWrap\" inputs=\"0\" hasInputFile=\"yes\" \n"
"               restartable=\"no\" isViz=\"no\"/>\n"
"  <application name=\"geomview\" inputs=\"1\" hasInputFile=\"no\" \n"
"               restartable=\"no\" isViz=\"yes\"/>\n"
"  <application name=\"FEAConsumer\" inputs=\"1\" hasInputFile=\"no\" \n"
"               restartable=\"no\" isViz=\"no\"/>\n"
"  <application name=\"lbe3d\" inputs=\"0\" hasInputFile=\"yes\" \n"
"               restartable=\"yes\" isViz=\"no\"/>\n"
"  <application name=\"lbe3dviz\" inputs=\"1\" hasInputFile=\"no\" \n"
"               restartable=\"no\" isViz=\"yes\"/>\n"
"  <application name=\"namd\" inputs=\"0\" hasInputFile=\"yes\" \n"
"               restartable=\"yes\" isViz=\"no\"/>\n"
"  <application name=\"vmd\" inputs=\"1\" hasInputFile=\"yes\" \n"
"               restartable=\"no\" isViz=\"yes\"/>\n"
"  <application name=\"mini_app\" inputs=\"0\" hasInputFile=\"no\" \n"
"               restartable=\"no\" isViz=\"no\"/>\n"
"  <application name=\"mini_app_para\" inputs=\"0\" hasInputFile=\"no\" \n"
"               restartable=\"no\" isViz=\"no\"/>\n"
"  <application name=\"sink\" inputs=\"1\" hasInputFile=\"no\" \n"
"               restartable=\"no\" isViz=\"no\"/>\n"
" </applications>\n"
"</launcher>\n"
);
